# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'douban' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for douban
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 4.0.0-beta2'
  pod 'ReactiveCocoa', '~> 5.0.0-rc.1'
end
